export const teamMembers = [
  {
    id: 1,
    name: 'Sarah Mitchell',
    email: 'sarah.mitchell@example.com',
    role: 'Admin',
    status: 'Active',
    last_active: '2026-09-07 09:42:18',
  },
  {
    id: 2,
    name: 'James Wilson',
    email: 'james.wilson@example.com',
    role: 'Developer',
    status: 'Active',
    last_active: '2026-09-07 09:15:44',
  },
  {
    id: 3,
    name: 'Emily Carter',
    email: 'emily.carter@example.com',
    role: 'Designer',
    status: 'Active',
    last_active: '2026-09-06 17:38:21',
  },
  {
    id: 4,
    name: 'Michael Brown',
    email: 'michael.brown@example.com',
    role: 'Developer',
    status: 'Away',
    last_active: '2026-09-06 14:12:09',
  },
  {
    id: 5,
    name: 'Olivia Davis',
    email: 'olivia.davis@example.com',
    role: 'Manager',
    status: 'Active',
    last_active: '2026-09-06 11:44:55',
  },
  {
    id: 6,
    name: 'Daniel Anderson',
    email: 'daniel.anderson@example.com',
    role: 'Developer',
    status: 'Inactive',
    last_active: '2026-09-04 16:22:31',
  },
  {
    id: 7,
    name: 'Sophia Taylor',
    email: 'sophia.taylor@example.com',
    role: 'Designer',
    status: 'Active',
    last_active: '2026-09-07 08:51:03',
  },
  {
    id: 8,
    name: 'Matthew Thomas',
    email: 'matthew.thomas@example.com',
    role: 'Developer',
    status: 'Active',
    last_active: '2026-09-05 19:27:46',
  },
  {
    id: 9,
    name: 'Isabella Moore',
    email: 'isabella.moore@example.com',
    role: 'Manager',
    status: 'Away',
    last_active: '2026-09-05 13:18:52',
  },
  {
    id: 10,
    name: 'Ethan Martin',
    email: 'ethan.martin@example.com',
    role: 'Developer',
    status: 'Active',
    last_active: '2026-09-06 09:34:17',
  },
  {
    id: 11,
    name: 'Ava Jackson',
    email: 'ava.jackson@example.com',
    role: 'Admin',
    status: 'Active',
    last_active: '2026-09-07 07:58:42',
  },
  {
    id: 12,
    name: 'Alexander White',
    email: 'alexander.white@example.com',
    role: 'Developer',
    status: 'Inactive',
    last_active: '2026-09-02 15:41:26',
  },
  {
    id: 13,
    name: 'Mia Harris',
    email: 'mia.harris@example.com',
    role: 'Designer',
    status: 'Active',
    last_active: '2026-09-06 18:05:11',
  },
  {
    id: 14,
    name: 'William Clark',
    email: 'william.clark@example.com',
    role: 'Manager',
    status: 'Active',
    last_active: '2026-09-07 09:02:37',
  },
  {
    id: 15,
    name: 'Charlotte Lewis',
    email: 'charlotte.lewis@example.com',
    role: 'Developer',
    status: 'Away',
    last_active: '2026-09-06 12:56:48',
  },
  {
    id: 16,
    name: 'Benjamin Lee',
    email: 'benjamin.lee@example.com',
    role: 'Developer',
    status: 'Active',
    last_active: '2026-09-05 16:33:04',
  },
  {
    id: 17,
    name: 'Amelia Walker',
    email: 'amelia.walker@example.com',
    role: 'Designer',
    status: 'Inactive',
    last_active: '2026-09-01 10:21:19',
  },
  {
    id: 18,
    name: 'Lucas Hall',
    email: 'lucas.hall@example.com',
    role: 'Developer',
    status: 'Active',
    last_active: '2026-09-07 08:27:55',
  },
  {
    id: 19,
    name: 'Harper Allen',
    email: 'harper.allen@example.com',
    role: 'Manager',
    status: 'Active',
    last_active: '2026-09-06 16:48:32',
  },
  {
    id: 20,
    name: 'Henry Young',
    email: 'henry.young@example.com',
    role: 'Developer',
    status: 'Away',
    last_active: '2026-09-05 11:17:43',
  },
  {
    id: 21,
    name: 'Evelyn Hernandez',
    email: 'evelyn.hernandez@example.com',
    role: 'Designer',
    status: 'Active',
    last_active: '2026-09-07 08:03:29',
  },
  {
    id: 22,
    name: 'Sebastian King',
    email: 'sebastian.king@example.com',
    role: 'Developer',
    status: 'Active',
    last_active: '2026-09-04 17:52:14',
  },
  {
    id: 23,
    name: 'Ella Wright',
    email: 'ella.wright@example.com',
    role: 'Admin',
    status: 'Active',
    last_active: '2026-09-07 09:51:06',
  },
  {
    id: 24,
    name: 'Jack Lopez',
    email: 'jack.lopez@example.com',
    role: 'Developer',
    status: 'Inactive',
    last_active: '2026-08-29 14:36:27',
  },
  {
    id: 25,
    name: 'Scarlett Hill',
    email: 'scarlett.hill@example.com',
    role: 'Designer',
    status: 'Away',
    last_active: '2026-09-03 09:44:51',
  },
  {
    id: 26,
    name: 'Owen Scott',
    email: 'owen.scott@example.com',
    role: 'Developer',
    status: 'Active',
    last_active: '2026-09-06 15:29:38',
  },
  {
    id: 27,
    name: 'Grace Green',
    email: 'grace.green@example.com',
    role: 'Manager',
    status: 'Active',
    last_active: '2026-09-07 07:41:22',
  },
  {
    id: 28,
    name: 'Theodore Adams',
    email: 'theodore.adams@example.com',
    role: 'Developer',
    status: 'Active',
    last_active: '2026-09-05 18:14:09',
  },
  {
    id: 29,
    name: 'Chloe Baker',
    email: 'chloe.baker@example.com',
    role: 'Designer',
    status: 'Inactive',
    last_active: '2026-08-31 13:07:45',
  },
  {
    id: 30,
    name: 'Jameson Nelson',
    email: 'jameson.nelson@example.com',
    role: 'Developer',
    status: 'Active',
    last_active: '2026-09-06 10:55:16',
  },
]
